name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Dependecies
        run: npm ci
      
      - name: Build
        run: npm run build
        
      - name: Save version
        id: version
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
        
      - name: Increase version
        run: npm version patch
        
      - name: Push new version
        run: git push
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag sankaristar/reactapp:${{steps.version.outputs.tag}}
        
      - name: Push to Docker Hub
        run: docker push sankaristar/reactapp:${{steps.version.outputs.tag}}
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            #!/bin/bash
            IMAGE_NAME="sankaristar/reactapp:${{steps.version.outputs.tag}}"
            CONTAINER_NAME="reactapp"
            PORT_MAPPING="8081:80"

            docker pull $IMAGE_NAME

            # Stop the existing container if running
            docker stop $CONTAINER_NAME || true

            # Remove the old container
            docker rm $CONTAINER_NAME || true

            # Run a new container with the latest image
            docker run --name $CONTAINER_NAME -d -p $PORT_MAPPING $IMAGE_NAME

            echo "Deployment complete!"       
